sudo: required
services:
- docker
language: java
dist: bionic
jdk:
- openjdk14
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_IMAGE=image-recognition-service-api:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: A87igNInGfVdj/9yymoK7E+Iyv8A8dtOSkbvQQJVV2B0FPN2H+JIYDZnf1sOzdarujVdgeYsWb/wFhUlbOwb1X8946HjU9ExHqZzhJPrnd1bQX8TXOBsVFqVp4WyuppMB257egXk9J3bFTuEsmyUu24Hyx8MFrMuAEs+yiZUtfiljbnAeUkqztJ0ITPQ9G52QiWifACk3qm+EXEMrbScxes5DtXYT7yhRCx/axnlbG/mEEj3nlSD4q/tHAxzrJxSnX3jlQz9F4ZOsYX1C12pSktt7n2Eua5XgQfRanzjc97VkiarzfJp2DmPyEcO8Xuf8+sSJxuzf3TBXNu04HOAxiHkl8U/ChBGXxr63XLuoDfMuNSsMKL0QZExoxlNDj+1V42zk2lo+GJDkBVrdsELJ9VVD689yPpvVF/6DK5WFuYcmqcr29RI4TKfk+/m5Wj3xOOwLiRocP5RjF+YNM/FBjamoWiWr3LELhwzHp2pPWMe/pegzxkRkBJgyjopC5w2A+PRTmMnwLjDMdbkd0xnqc/DwSpvMAn3saW0w3FEyYTR1XAG2j8vD5XRH1Qw0+bCBA/SJM9oa1vADcydRfudj2k73chEJe1ywEGGYtHD2uAKPvEOxB5h1b1ndE9kLja28E6mD3do1gQhXgjWTw35XFpE3Z5ccEgsQWQcRQMDQwg=
  - secure: coNrke3aJPfLO4guSlgx5E+6/kbAs1RPhFHtOHOwTsUePk4kJyAPX/i49h3RN9WmsU6WzhfC0/3nwYFWMNHmQirMX1FaNR/CHBpAexk377huJmyUkjJjdXbTBgBLUdfmqTpq780RXQ3H2fC2LSYYJuo8sqYGRyXcwvHyL47TAVKarryRaB8HYELIdHgPFCUg9JYSOgAnXWcnUyV/rtY7t3tJHbqc5QRWrXFiiZEYAfTbMYr5cxOyndarQtnWo7vkKQF4Hc9v2PaUQay7aNiagtFKj48N3F8Z1GGfL3gPaqfucznK4AI84ax8Tyt8UxJNATB2Q5X3WsPuK43mt/TnW7qcupvXTNRH2tVo713H8aI5o+TrBcS+8ICW3ADxCiJ2cQmUVook3RzEnN/Xs2M9DJv7zcU/5JUHV9gmGhuOnw2Hz78qlJ3leIFTlj33XkduDw2Btfhib2q1JwfEzbarZXIhAX1BzYnuTr74e8GA8CcsfKlohasUmvkQKf3nyf4QBFp4HmK/m5Nf0h/BCEBBBF8Dh4OuEm5aYcL+tgH+Wh7A5AEmBdwErinFLWBNd4zmPM4qhtk6uYKxC4w8C6JInk/ytxfW7Lcg/w4KW3NJLhGfbfBCHhw3RT21xzBm5dCnBi9nqbd4B5ORK+042xmhymH3Sa0IadI0MOc6VMSIc2U=
script:
- mvn clean package -U
- docker build -t "$DOCKER_USERNAME"/"$DOCKER_IMAGE" -t "$DOCKER_USERNAME"/"image-recognition-service-api:latest"
  .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_USERNAME"/"$DOCKER_IMAGE"
- docker push "$DOCKER_USERNAME"/"image-recognition-service-api:latest"
