apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-recognition-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-recognition-service
  template:
    metadata:
      labels:
        app: image-recognition-service
    spec:
      containers:
        - image: anzemur/image-recognition-service-api:latest
          name: image-recognition-service
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-url
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: access-key-id
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: secret-key

---

apiVersion: v1
kind: Service
metadata:
  name: image-recognition-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: server
  selector:
    app: image-recognition-service