kumuluzee:
  name: image-recognition-service-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  metrics:
    web-instrumentation:
      - name: metrics-enpoint
        url-pattern: /metrics/*
