kumuluzee:
  name: image-recognition-service-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  cors-filter:
    annotations:
      image-recognition-resource:
        allow-origin: "*"
        allow-subdomains: true
        supported-methods: "GET, POST, DELETE, HEAD, OPTIONS, PUT"
  metrics:
    web-instrumentation:
      - name: metrics-enpoint
        url-pattern: /metrics/*
